[package]
name = "gm8emulator"
version = "0.1.0"
authors = ["Adamcake", "viri"]
license = "GPL-2.0-only"
edition = "2018"
default-run = "gm8emulator"

[build-dependencies]
gl_generator = "0.14.0"

[dependencies]
bincode = "1.2"
cfg-if = "0.1"
chrono = "0.4"
encoding_rs = "0.8.23"
getopts = "0.2.21"
glob = "0.3.0"
gm8exe = { git = "https://github.com/OpenGM8/GM8Decompiler.git" }
gmio = { path = "../gmio" }
gml-parser = { path = "../gml-parser", features = ["runner-serde-derives"] }
hex = "0.4.2"
image = "0.23.6"
indexmap = { version = "1.3.2", features = ["serde-1"] }
memoffset = "0.5.3"
rand = "0.7.2" # for seeding, not generating
rect_packer = "0.2.1"
rodio = "0.12"
rust-ini = "0.15.2"
serde = { version = "1.0", features = ["derive", "rc"] }
shared = { path = "../shared" }

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3"
features = ["commctrl", "errhandlingapi", "libloaderapi", "timeapi", "winbase", "windowsx", "wingdi", "winuser"]

[target.'cfg(target_os = "linux")'.dependencies.x11]
version = "2.18.2"
features = ["xlib"]
